// ==========================================
// بنك الأسئلة المركزي لجميع المواد
// ==========================================

// 1. أسئلة تصميم المختبرات (120 سؤال)
const labQuestions = [
    
    { q: "Why is good laboratory design important?", a: ["Only to reduce construction costs", "To ensure safety, efficiency, and compliance with standards", "Only to improve building appearance", "To reduce the number of workers"], c: 1 },
    { q: "A well-planned laboratory should consider the specific scientific and operational needs of:", a: ["Only academic institutions", "Only industrial facilities", "The research or medical work conducted within it", "Only healthcare settings"], c: 2 },
    { q: "Laboratory design may vary depending on whether the laboratory is in:", a: ["A shopping center", "A healthcare setting, academic institution, or industrial facility", "A residential house only", "A sports complex"], c: 1 },
    { q: "The lecture covers laboratory design principles including:", a: ["Music, art, and architecture", "Layout, safety, equipment, and environmental considerations", "Marketing and management only", "Finance and accounting"], c: 1 },
    { q: "The purpose of a laboratory may include all of the following except:", a: ["Research", "Diagnostics", "Education", "Transportation"], c: 3 },
    { q: "Different laboratory purposes require:", a: ["The same design requirements", "Different design requirements", "No design planning", "Only decorative changes"], c: 1 },
    { q: "The design of a laboratory should support:", a: ["Only current building style", "The type of testing and research activities planned", "Only furniture arrangement", "External appearance only"], c: 1 },
    { q: "Laboratory adaptability is important to meet future changes in:", a: ["Paint color", "Technology or research focus", "Parking area only", "Staff uniforms"], c: 1 },
    { q: "Which of the following is listed as an effective laboratory design principle?", a: ["Noise increase", "Safety", "Random layout", "Reduced ventilation"], c: 1 },
    { q: "Safety protocols should be embedded into the layout to protect:", a: ["Only users", "Only equipment", "Both users and the environment", "Only visitors"], c: 2 },
    { q: "Which of the following must be considered under safety in laboratory design?", a: ["Wall color", "Hazardous materials, biosafety levels, and contamination risks", "Number of windows only", "Cafeteria size"], c: 1 },
    { q: "Workflow efficiency in laboratory design means that the layout should:", a: ["Increase unnecessary movement", "Minimize unnecessary movement", "Place equipment randomly", "Reduce storage areas only"], c: 1 },
    { q: "For efficient workflow, equipment and materials should be:", a: ["Hidden from users", "Logically positioned", "Stored outside the laboratory", "Moved daily"], c: 1 },
    { q: "Flexibility in laboratory design is important because:", a: ["Scientific work often changes", "Laboratories never change", "Equipment is never replaced", "Safety rules are removed"], c: 0 },
    { q: "Laboratories should be designed with modular features to allow:", a: ["Easy reconfiguration", "Permanent fixed arrangement only", "Reduced lighting", "Less storage space"], c: 0 },
    { q: "Energy-efficient laboratory design aims to:", a: ["Increase environmental impact", "Minimize environmental impact", "Eliminate all equipment", "Reduce user comfort"], c: 1 },
    { q: "Laboratories are typically divided into zones based on:", a: ["Paint type", "Function", "Window size", "Employee age"], c: 1 },
    { q: "Examples of laboratory zones mentioned in the text include:", a: ["Sleeping areas and kitchens", "Preparation areas, storage, administrative spaces, and specialized equipment areas", "Sports areas and libraries", "Elevators and parking zones"], c: 1 },
    { q: "The design must account for smooth movement flow in order to minimize:", a: ["Energy use", "Cross-contamination", "Lighting levels", "Furniture use"], c: 1 },
    { q: "Proper ventilation in a laboratory is essential to:", a: ["Increase noise", "Maintain air quality, remove contaminants, and ensure comfort and safety", "Replace safety protocols", "Reduce the number of workers"], c: 1 },
    { q: "Why does good laboratory design play a critical role?", a: ["It reduces staff salaries", "It ensures safety, efficiency, and compliance with standards", "It replaces all laboratory equipment", "It eliminates the need for supervision"], c: 1 },
    { q: "A well-planned laboratory considers the specific scientific and operational needs of:", a: ["Only the building owner", "The research or medical work conducted in it", "Only the cleaning staff", "The administrative office only"], c: 1 },
    { q: "Laboratory design applies to laboratories in:", a: ["Healthcare settings only", "Academic institutions only", "Industrial facilities only", "Healthcare, academic, and industrial facilities"], c: 3 },
    { q: "The lecture covers all of the following except:", a: ["Layout", "Safety", "Equipment", "Marketing"], c: 3 },
    { q: "One of the first questions in laboratory design is whether the lab is for:", a: ["Sports or entertainment", "Research, diagnostics, education, or manufacturing", "Housing or transport", "Cooking or storage only"], c: 1 },
    { q: "According to the text, each laboratory purpose needs:", a: ["The same design requirements", "Different design requirements", "No design requirements", "Only decorative changes"], c: 1 },
    { q: "The design should support the type of:", a: ["Furniture colors", "Testing and research activities planned", "Building materials only", "Lighting style only"], c: 1 },
    { q: "Laboratory design should consider adaptability to future:", a: ["Fashion trends", "Changes in technology or research focus", "Staff uniforms", "Construction companies"], c: 1 },
    { q: "Safety is listed in the text as a:", a: ["Minor optional feature", "Design principle", "Financial issue", "Decoration standard"], c: 1 },
    { q: "Safety protocols need to be embedded into the layout to protect:", a: ["Only users", "Only equipment", "Both users and the environment", "Only visitors"], c: 2 },
    { q: "Which of the following must be considered in laboratory safety design?", a: ["Wall paint only", "Hazardous materials", "Cafeteria layout", "Parking area size"], c: 1 },
    { q: "Another safety-related factor mentioned in the text is:", a: ["Window curtains", "Biosafety levels", "Elevator speed", "Office decoration"], c: 1 },
    { q: "Contamination risks must be considered as part of:", a: ["Laboratory safety", "Exterior building design only", "Furniture arrangement only", "Administrative planning only"], c: 0 },
    { q: "Workflow efficiency means the design should:", a: ["Increase unnecessary movement", "Facilitate efficient workflow", "Reduce all equipment", "Eliminate storage"], c: 1 },
    { q: "To improve workflow efficiency, the layout should minimize:", a: ["Ventilation", "Unnecessary movement", "Safety signs", "Workbenches"], c: 1 },
    { q: "For efficient workflow, equipment and materials should be:", a: ["Randomly positioned", "Logically positioned", "Hidden from users", "Stored outside the lab"], c: 1 },
    { q: "Flexibility in laboratory design is important because:", a: ["Scientific work often changes", "Labs never change", "Equipment is always fixed forever", "Research does not develop"], c: 0 },
    { q: "Flexibility is achieved by using:", a: ["Fragile materials", "Modular features", "Less equipment", "Locked doors only"], c: 1 },
    { q: "Modular features allow laboratories to be:", a: ["Permanently fixed", "Easily reconfigured", "Less safe", "More expensive only"], c: 1 },
    { q: "Energy efficiency is important because many laboratories:", a: ["Use very little energy", "Consume high amounts of energy", "Have no electrical systems", "Depend only on sunlight"], c: 1 },
    { q: "Energy-efficient laboratory design should aim to minimize:", a: ["Number of workers", "Environmental impact", "Safety procedures", "Storage capacity"], c: 1 },
    { q: "Laboratory layout includes consideration of:", a: ["Zoning", "Advertising", "Uniform color", "Employee salary"], c: 0 },
    { q: "Laboratories are typically divided into zones based on:", a: ["Shape of the building", "Function", "Number of chairs", "Wall height"], c: 1 },
    { q: "Which of the following is mentioned as a laboratory zone?", a: ["Preparation area", "Dining room", "Sleeping area", "Lobby shop"], c: 0 },
    { q: "Which of the following is also listed as a laboratory zone?", a: ["Playground", "Storage", "Garage", "Bathroom only"], c: 1 },
    { q: "Administrative spaces are mentioned in the text as part of:", a: ["Zoning", "Waste management", "Lighting", "User comfort only"], c: 0 },
    { q: "Specialized equipment areas are included under:", a: ["Safety", "Zoning", "Fire protection only", "Furniture design only"], c: 1 },
    { q: "Movement flow in the laboratory should be designed to be:", a: ["Confusing", "Smooth", "Circular only", "Restricted completely"], c: 1 },
    { q: "Smooth movement flow helps to minimize:", a: ["Productivity", "Cross-contamination", "User comfort", "Lighting intensity"], c: 1 },
    { q: "Proper ventilation is essential to maintain:", a: ["Wall color", "Air quality", "Furniture size", "Room decoration"], c: 1 },
    { q: "Ventilation also helps to:", a: ["Remove contaminants", "Reduce storage", "Eliminate workstations", "Replace safety rules"], c: 0 },
    { q: "Proper ventilation helps ensure user:", a: ["Comfort and safety", "Salary and training", "Speed and silence", "Decoration and style"], c: 0 },
    { q: "Which of the following is one of the key elements in laboratory design?", a: ["Workbenches and workstations", "Cafeteria design", "Parking system", "Reception desk only"], c: 0 },
    { q: "Workbenches and workstations should be:", a: ["Fragile and decorative", "Durable, chemical-resistant, and well designed", "Temporary and soft", "Light and foldable only"], c: 1 },
    { q: "Storage in laboratories may include:", a: ["Open shelves for all materials", "Locked cabinets for hazardous materials", "Outdoor storage only", "Wooden boxes only"], c: 1 },
    { q: "Storage should also include cold storage for:", a: ["Office supplies", "Temperature-sensitive items", "Heavy machinery", "Furniture"], c: 1 },
    { q: "Proper lighting in a laboratory helps to reduce:", a: ["Storage needs", "Errors", "Ventilation", "Waste only"], c: 1 },
    { q: "Proper lighting also improves:", a: ["Focus", "Noise", "Heat", "Movement speed"], c: 0 },
    { q: "Which of the following is essential in laboratories that handle chemicals or biohazards?", a: ["Waiting rooms", "Fume hoods and biosafety cabinets", "Decorative windows", "Soft seating"], c: 1 },
    { q: "Waste management systems should be integrated for:", a: ["Food waste only", "Chemical, biological, and radioactive waste", "Paper waste only", "Office waste only"], c: 1 },
    { q: "Fire extinguishers are essential under:", a: ["User comfort", "Fire safety", "Lighting", "Zoning"], c: 1 },
    { q: "Clear emergency exits are part of:", a: ["Fire safety", "Storage", "Equipment layout", "Energy efficiency only"], c: 0 },
    { q: "Emergency protocols should provide easy access to:", a: ["Coffee machines", "Emergency stations", "Administrative desks", "Research offices"], c: 1 },
    { q: "An example of an emergency station mentioned in the text is:", a: ["Refrigerator", "Eyewash station", "Workbench", "File cabinet"], c: 1 },
    { q: "Another emergency station mentioned is:", a: ["Shower", "Camera", "Computer", "Air conditioner"], c: 0 },
    { q: "BSL in laboratory design stands for:", a: ["Biological Safety Load", "Biosafety Levels", "Basic Science Laboratory", "Biosecure Storage Limit"], c: 1 },
    { q: "Biosafety levels define:", a: ["Furniture quality", "Containment levels for laboratories handling biological materials", "Lighting intensity", "Water pressure"], c: 1 },
    { q: "Laboratories are often described in the text as:", a: ["Relaxed environments", "High-stress environments", "Outdoor environments", "Silent environments"], c: 1 },
    { q: "Because laboratories are often high-stress environments, designs should consider:", a: ["User comfort", "Wall colors only", "Equipment cost only", "Parking space only"], c: 0 },
    { q: "One way to improve user comfort is by providing:", a: ["Fixed workstations only", "Adjustable workstations", "Less lighting", "No seating"], c: 1 },
    { q: "The text also mentions the use of:", a: ["Consumable furniture", "Steel-only furniture", "Outdoor furniture", "Foldable beds"], c: 0 },
    { q: "Environmental considerations include:", a: ["Sound systems", "Water and energy conservation", "Office decorations", "Transportation design"], c: 1 },
    { q: "Sustainable laboratory design incorporates:", a: ["Low-flow fixtures", "High-flow fixtures only", "No plumbing", "Decorative fixtures only"], c: 0 },
    { q: "Sustainable design also includes:", a: ["Energy-efficient equipment", "More paper use", "Larger rooms only", "More lighting errors"], c: 0 },
    { q: "Good laboratory design supports compliance with:", a: ["Fashion rules", "Standards", "Personal opinions", "Building color codes only"], c: 1 },
    { q: "The design requirements of a laboratory depend on its:", a: ["Purpose and function", "Exterior paint", "Number of floors only", "Window shape only"], c: 0 },
    { q: "Research, diagnostics, education, and manufacturing are examples of laboratory:", a: ["Furniture types", "Purposes", "Hazards", "Lighting systems"], c: 1 },
    { q: "The laboratory design should be able to meet future:", a: ["Noise levels", "Changes and advancements", "Staff vacations", "Paint replacements"], c: 1 },
    { q: "Hazardous materials must be considered in order to improve:", a: ["Decoration", "Safety", "Furniture selection", "Administrative planning"], c: 1 },
    { q: "A laboratory layout should support smooth flow mainly to prevent:", a: ["Overspending", "Cross-contamination", "Poor furniture quality", "Color mismatch"], c: 1 },
    { q: "Preparation areas are an example of laboratory:", a: ["Waste systems", "Zones", "Furniture types", "Emergency stations"], c: 1 },
    { q: "Storage areas are usually separated because of laboratory:", a: ["Zoning by function", "User comfort only", "Lighting requirements only", "Exterior structure"], c: 0 },
    { q: "Administrative spaces belong to laboratory layout under:", a: ["Fire safety", "Zoning", "User comfort", "Lighting design"], c: 1 },
    { q: "Specialized equipment areas are designed based on:", a: ["Function", "Furniture style", "Worker age", "Building color"], c: 0 },
    { q: "The need to remove contaminants is mainly linked with:", a: ["Storage", "Ventilation and airflow", "User comfort", "Workbench design"], c: 1 },
    { q: "Chemical-resistant workstations are important because laboratories may handle:", a: ["Clothing", "Chemicals", "Furniture only", "Paper only"], c: 1 },
    { q: "Locked cabinets are especially needed for:", a: ["Office files", "Hazardous materials", "General furniture", "Books only"], c: 1 },
    { q: "Cold storage is important for items that are:", a: ["Oversized", "Temperature-sensitive", "Fragile only", "Cheap"], c: 1 },
    { q: "One benefit of proper lighting is improved:", a: ["Focus", "Waste generation", "Noise control", "Airflow speed"], c: 0 },
    { q: "Fume hoods are particularly essential in labs handling:", a: ["Biohazards or chemicals", "Furniture only", "Administrative work only", "Dry office materials"], c: 0 },
    { q: "Biosafety cabinets are essential when laboratories handle:", a: ["Office documents", "Chemicals or biohazards", "Only furniture", "Only lighting tools"], c: 1 },
    { q: "Integrated waste systems are needed for radioactive waste because of:", a: ["Waste management design", "User comfort", "Administrative planning", "Decorative planning"], c: 0 },
    { q: "Emergency exits should be:", a: ["Hidden", "Clear", "Locked", "Decorative only"], c: 1 },
    { q: "Easy access to eyewash stations is part of:", a: ["Emergency protocols", "Equipment storage", "Lighting design", "Modularity"], c: 0 },
    { q: "Containment levels are particularly important in labs handling:", a: ["Furniture", "Biological materials", "Administrative paperwork", "Lighting cables"], c: 1 },
    { q: "High-stress laboratory environments require attention to:", a: ["User comfort", "Storage color", "Exterior signs only", "Marketing plans"], c: 0 },
    { q: "Adjustable workstations are included in the text under:", a: ["User comfort", "Fire safety", "Zoning", "Waste disposal"], c: 0 },
    { q: "Water conservation is considered under:", a: ["Safety protocols", "Environmental considerations", "Workbench design", "Administrative spaces"], c: 1 },
    { q: "Low-flow fixtures are part of:", a: ["Sustainable design", "Emergency protocols", "Storage systems", "Fire safety"], c: 0 },
    { q: "Energy-efficient equipment helps support:", a: ["Sustainable laboratory design", "More contamination", "Less safety", "More movement"], c: 0 },
    { q: "A laboratory handling biological materials must consider:", a: ["Biosafety levels", "Furniture cost only", "Exterior walls only", "Window placement only"], c: 0 },
    { q: "A key goal of laboratory design is to improve both safety and:", a: ["Decoration", "Efficiency", "Noise", "Clothing storage"], c: 1 },
    { q: "The position of equipment and materials should be planned in a:", a: ["Random way", "Logical way", "Decorative way", "Temporary way"], c: 1 },
    { q: "Flexibility helps laboratories respond to changes in:", a: ["Research focus", "Paint suppliers", "Parking rules", "Cafeteria menus"], c: 0 },
    { q: "One reason labs should be modular is to support:", a: ["Easy reconfiguration", "Permanent fixed walls only", "Reduced safety", "Lower lighting only"], c: 0 },
    { q: "Removing contaminants from laboratory air is the job of:", a: ["Storage systems", "Ventilation and airflow", "Workbenches", "Waste bins"], c: 1 },
    { q: "The text describes workbenches as needing to be:", a: ["Soft and decorative", "Durable and chemical-resistant", "Disposable only", "Metallic only"], c: 1 },
    { q: "Proper lighting mainly contributes to reducing:", a: ["Errors", "Cabinets", "Containment", "Water use"], c: 0 },
    { q: "Chemical, biological, and radioactive waste should be handled through:", a: ["Open containers", "Integrated waste disposal systems", "General office bins", "Outdoor dumping"], c: 1 },
    { q: "The phrase “support the type of testing and research activities planned” refers to:", a: ["Purpose and function", "User comfort only", "Furniture design only", "Administrative planning only"], c: 0 },
    { q: "Cross-contamination is mainly reduced by proper:", a: ["Movement flow", "Paint choice", "Office planning", "Wall thickness"], c: 0 },
    { q: "The laboratory should be designed not only for present needs but also for:", a: ["Future changes", "Decoration only", "Furniture replacement only", "Visitor comfort only"], c: 0 },
    { q: "One environmental goal in laboratory design is conservation of:", a: ["Water and energy", "Paper and books", "Doors and windows", "Tables and chairs"], c: 0 },
    { q: "Fire extinguishers are important because they are part of:", a: ["Fire safety", "Modularity", "Storage planning", "User comfort"], c: 0 },
    { q: "The text emphasizes that design should protect users and:", a: ["Suppliers", "The environment", "Visitors only", "Furniture"], c: 1 },
    { q: "Laboratories handling chemicals require special elements such as:", a: ["Fume hoods", "Dining tables", "Sports equipment", "Soundproof curtains"], c: 0 },
    { q: "Emergency showers are included under:", a: ["Emergency protocols", "Storage", "Zoning", "Lighting"], c: 0 },
    { q: "The adaptability of laboratory design is linked to future:", a: ["Advances in technology", "Paint brands", "Office furniture", "Building age only"], c: 0 },
    { q: "One of the design principles specifically focused on environmental impact is:", a: ["Energy efficiency", "Zoning", "Lighting", "Storage"], c: 0 },
    { q: "Overall, the text presents laboratory design as a balance of safety, efficiency, and:", a: ["Compliance with standards", "Entertainment", "Decoration", "Advertising"], c: 0 }
];

// 2. أسئلة جهاز الطرد المركزي (100 سؤال)
const centrifugeQuestions = [
    
    {q: "A centrifuge uses centrifugal force primarily for:", a: ["Heating samples", "Separating solids suspended in a liquid by sedimentation", "Creating magnetic fields", "Measuring pH"], c: 1},
    {q: "In the text, centrifugal force is defined as the force generated when an object:", a: ["Moves in a straight line", "Rotates around a single point", "Vibrates randomly", "Floats on a liquid"], c: 1},
    {q: "Rotational movements in a centrifuge allow forces much greater than:", a: ["Atmospheric pressure", "Gravity", "Surface tension", "Osmotic pressure"], c: 1},
    {q: "Centrifuges are generally used in laboratories for:", a: ["Producing antibodies", "Separation of solid components from biological liquids through sedimentation", "Sterilizing glassware", "Measuring blood glucose"], c: 1},
    {q: "Sedimentation of suspended and some dissolved particles occurs due to:", a: ["Heat", "Centrifugal force", "Magnetism", "Light"], c: 1},
    {q: "One operation principle is that a centrifuge separates particles from samples such as:", a: ["Saliva and sweat", "Blood or urine", "Hair and nails", "Bone and cartilage"], c: 1},
    {q: "Separating particles from blood or urine gives:", a: ["Whole blood", "Cell-free plasma or serum", "Pure water", "Solid fat only"], c: 1},
    {q: "A centrifuge can separate two kinds of liquids with different:", a: ["Colors", "Densities", "Temperatures", "Odors"], c: 1},
    {q: "An example given is separating lipid components from:", a: ["Red blood cells only", "Other components of plasma or serum", "Urine crystals", "Air bubbles"], c: 1},
    {q: "The motor in a centrifuge is described as:", a: ["A part that stores samples", "An electric motor that helps to drive", "A part that locks the lid only", "A part that measures density"], c: 1},
    {q: "The control panel is placed on the:", a: ["Rotor hub", "Front casing", "Bottom of the chamber", "Drive shaft"], c: 1},
    {q: "The control panel serves the purpose of:", a: ["Cooling the rotor", "Controlling centrifuge operation", "Filtering dissolved particles", "Measuring friction"], c: 1},
    {q: "The entire system is housed within a:", a: ["Latch", "Chamber", "Screen", "Tube cap"], c: 1},
    {q: "Rotors in centrifuges are devices that house:", a: ["The control panel", "The tubes with the samples", "The chamber walls", "The latch springs"], c: 1},
    {q: "Centrifuge rotors are designed to generate rotation speed that can bring about:", a: ["Heating of samples", "Separation of components in a sample", "Chemical reactions", "Electrical conduction"], c: 1},
    {q: "\"Sample\" refers to:", a: ["The part that drives the rotor", "That to be separated", "The display screen", "The chamber lining"], c: 1},
    {q: "The latch keeps the centrifuge lid closed in the event of:", a: ["Low speed", "Tube breakage or other problems while operating", "High room temperature", "Low density liquids"], c: 1},
    {q: "A centrifuge includes a:", a: ["Rotor", "Microscope lens", "X-ray tube", "Ultrasound probe"], c: 0},
    {q: "One listed part of a centrifuge is the:", a: ["Condenser", "Lid", "Beaker stand", "Pipette tip"], c: 1},
    {q: "Another listed part is the:", a: ["Screen", "Burner", "Thermostat", "Dialysis membrane"], c: 0},
    {q: "A listed part also includes the:", a: ["Drive shaft", "Incubator", "Spectrophotometer", "Autoclave chamber"], c: 0},
    {q: "One safety precaution is to ensure:", a: ["A soft, uneven surface", "A sturdy, level work surface", "The lid is open during operation", "Tubes are loosely placed"], c: 1},
    {q: "Balancing the centrifuge is important because an unbalanced centrifuge may:", a: ["Improve separation", "Cause significant damage and injure the operator", "Reduce density differences", "Prevent pelleting completely"], c: 1},
    {q: "To balance the centrifuge, all sample tubes should be:", a: ["Randomly filled", "Evenly filled", "Left empty", "Filled with air"], c: 1},
    {q: "If extra tubes are needed for balancing, fill them with:", a: ["Oil only", "Water or a liquid of similar density to the sample", "Alcohol only", "Mercury"], c: 1},
    {q: "During operation, you should:", a: ["Open the lid to check progress", "Not open the lid while the rotor is moving", "Shake the centrifuge gently", "Remove tubes mid-run"], c: 1},
    {q: "Many centrifuges have a \"safety shutoff,\" which:", a: ["Instantly stops the rotor motion", "Only stops power to the rotor", "Removes friction", "Opens the lid automatically"], c: 1},
    {q: "Even after power is cut, the rotor will still spin due to its:", a: ["Density", "Inertia", "Temperature", "Color"], c: 1},
    {q: "The rotor slows to a stop mainly by:", a: ["Magnetism", "Friction", "Diffusion", "Flotation"], c: 1},
    {q: "If the centrifuge is shaking, the text says to:", a: ["Increase speed", "Pull the plug", "Open the lid", "Add more liquid"], c: 1},
    {q: "The text says a little vibration is:", a: ["Always dangerous", "Normal", "Proof of tube breakage", "A reason to remove the rotor"], c: 1},
    {q: "Excessive shaking can mean:", a: ["Higher accuracy", "Danger", "Better density gradients", "Faster pelleting without risk"], c: 1},
    {q: "If shaking occurs, first double check that:", a: ["The lid is unlocked", "The tubes are correctly balanced", "The chamber is wet", "The rotor is removed"], c: 1},
    {q: "If balancing does not resolve shaking, do not operate the centrifuge until:", a: ["The room temperature increases", "It has been serviced by the manufacturer or dealer", "You add more water to samples", "You change the screen"], c: 1},
    {q: "Sedimentation force on a particle is opposed by:", a: ["Heat, light, magnetism", "Flotation force, frictional resistance, diffusion", "Pressure, volume, temperature", "Voltage, current, resistance"], c: 1},
    {q: "One listed opposing factor is:", a: ["Radiation", "Flotation force", "Evaporation", "Oxidation"], c: 1},
    {q: "Another opposing factor is:", a: ["Frictional resistance", "Color intensity", "Electrical conductivity", "Boiling"], c: 0},
    {q: "Another opposing factor is:", a: ["Condensation", "Diffusion", "Reflection", "Refraction"], c: 1},
    {q: "A fixed angle rotor is described as one where sedimenting particles travel:", a: ["A very long distance", "A short distance before pelleting", "No distance at all", "Only across tube diameter"], c: 1},
    {q: "Fixed angle rotors typically have:", a: ["Longer run time", "Shorter run time", "No pelleting", "No samples"], c: 1},
    {q: "The text states the most widely used rotor type is:", a: ["Swinging buckets", "Vertical tube", "Fixed angle", "Almost vertical tube"], c: 2},
    {q: "Swinging bucket rotors are characterized by:", a: ["Short travel distance for particles", "Longer distance of travel", "Tubes parallel to the axis at all times", "Bands forming across diameter only"], c: 1},
    {q: "A longer travel distance in swinging buckets may allow better separation in:", a: ["Heat gradient mixing", "Density gradient centrifugation", "Magnetic separation", "Filtration"], c: 1},
    {q: "Swinging bucket rotors make it easier to withdraw:", a: ["Pellet without disturbing supernatant", "Supernatant without disturbing pellet", "Rotor without stopping", "Lid without latch"], c: 1},
    {q: "Vertical tube rotors keep tubes:", a: ["Horizontal to the floor", "Parallel to the rotational axis", "At fixed angles to the axis", "Randomly aligned"], c: 1},
    {q: "In vertical tube rotors, bands form across the tube's:", a: ["Length, not diameter", "Diameter, not length", "Lid surface only", "Bottom only"], c: 1},
    {q: "Almost vertical tube rotors are used for gradient centrifugation when:", a: ["All components participate fully", "Some sample components do not participate in the gradient", "Only solids are present", "Only lipids are present"], c: 1},
    {q: "Which option correctly pairs \"fixed angle\" with its key feature?", a: ["Long travel distance for better gradients", "Short travel distance before pelleting", "Bands across diameter, not length", "Best for when components do not participate in gradients"], c: 1},
    {q: "Which option correctly pairs \"swinging buckets\" with a key advantage?", a: ["Shorter run time always", "Easier to withdraw supernatant without disturbing pellet", "Tubes remain parallel to axis", "Bands form across diameter only"], c: 1},
    {q: "Which rotor type is described as \"keeps tubes parallel to the rotational axis\"?", a: ["Fixed angle", "Swinging buckets", "Vertical tube", "Almost vertical tube"], c: 2},
    {q: "Which rotor type forms bands across diameter rather than length?", a: ["Fixed angle", "Swinging buckets", "Vertical tube", "Almost vertical tube"], c: 2},
    {q: "The latch is important because it keeps the lid closed in case of:", a: ["High density gradients", "Tube breakage or other problems during operation", "Low vibration", "Correct balancing"], c: 1},
    {q: "Which part is directly described as helping to \"drive\"?", a: ["Chamber", "Motor", "Lid", "Screen"], c: 1},
    {q: "Which part is described as being on the front casing?", a: ["Rotor", "Control panel", "Latch", "Drive shaft"], c: 1},
    {q: "Which part houses the entire system?", a: ["Lid", "Chamber", "Screen", "Sample tube"], c: 1},
    {q: "Which part houses the tubes with samples?", a: ["Screen", "Rotor", "Latch", "Control panel"], c: 1},
    {q: "Which statement is consistent with the text's definition of centrifugation outcomes?", a: ["Only suspended particles sediment", "Suspended and some dissolved particles can sediment", "Only dissolved particles sediment", "No particles sediment"], c: 1},
    {q: "The text mentions centrifuges are used in the lab for:", a: ["Conducting multiple tests and treatments", "Generating X-rays", "Producing vaccines", "Measuring ECG"], c: 0},
    {q: "According to the text, balancing requires tubes to be:", a: ["Unevenly filled to create gradients", "Evenly filled", "Filled to different volumes", "Filled with oil only"], c: 1},
    {q: "The safety shutoff stops:", a: ["Rotor motion instantly", "Power to the rotor only", "Friction instantly", "Diffusion instantly"], c: 1},
    {q: "The rotor continues to spin after shutoff because of:", a: ["Flotation", "Inertia", "Diffusion", "Sedimentation"], c: 1},
    {q: "The rotor slows until it stops due to:", a: ["Friction", "Flotation", "Diffusion", "Electricity"], c: 0},
    {q: "When shaking occurs, the first troubleshooting step is to:", a: ["Increase speed", "Double check tube balance", "Open the lid", "Remove the chamber"], c: 1},
    {q: "If shaking persists after balancing, the text instructs to:", a: ["Keep running", "Stop using until serviced by manufacturer/dealer", "Replace samples with water", "Remove the rotor while spinning"], c: 1},
    {q: "Which of the following is NOT listed as opposing sedimentation force?", a: ["Flotation force", "Frictional resistance", "Diffusion", "Gravity"], c: 3},
    {q: "Which list includes ONLY centrifuge parts named in the text?", a: ["Motor, control panel, chamber, rotor", "Spectrophotometer, incubator, rotor, chamber", "Autoclave, motor, microscope, latch", "Centrifuge, X-ray tube, screen, chamber"], c: 0},
    {q: "Which option includes a part explicitly listed in the text?", a: ["Pipette", "Lid", "Refrigerator", "pH meter"], c: 1},
    {q: "Which part is named as \"Drive shaft\"?", a: ["A safety precaution", "A centrifuge part", "A rotor type", "An opposing force"], c: 1},
    {q: "Which rotor type is linked to \"shorter run time\"?", a: ["Swinging buckets", "Vertical tube", "Fixed angle", "Almost vertical tube"], c: 2},
    {q: "Which rotor type is linked to \"longer distance of travel\"?", a: ["Fixed angle", "Swinging buckets", "Vertical tube", "Almost vertical tube"], c: 1},
    {q: "Which rotor type is linked to \"easier to withdraw supernatant\"?", a: ["Fixed angle", "Swinging buckets", "Vertical tube", "Almost vertical tube"], c: 1},
    {q: "Which rotor type is linked to \"bands across diameter\"?", a: ["Fixed angle", "Swinging buckets", "Vertical tube", "Almost vertical tube"], c: 2},
    {q: "Which rotor type is specifically mentioned for gradient centrifugation with partial participation?", a: ["Fixed angle", "Swinging buckets", "Vertical tube", "Almost vertical tube"], c: 3},
    {q: "The centrifuge separates solids suspended in liquid by:", a: ["Filtration", "Sedimentation", "Evaporation", "Crystallization"], c: 1},
    {q: "The text indicates centrifuges can separate liquids of:", a: ["Equal density only", "Diverse density", "Unknown temperature only", "Identical composition only"], c: 1},
    {q: "Which example of liquid separation is given?", a: ["Separating glucose from water", "Separating lipid components from other components of plasma/serum", "Separating salt from sugar", "Separating oxygen from nitrogen"], c: 1},
    {q: "Cell-free plasma or serum is obtained for:", a: ["Painting slides", "Different tests", "Heating experiments", "Drying samples"], c: 1},
    {q: "The text describes centrifugal force as produced by:", a: ["Free fall", "Rotation around a single point", "Electrical current", "Chemical reaction"], c: 1},
    {q: "The safety list includes the instruction:", a: ["Always operate on a shaky surface", "Ensure a sturdy, level work surface", "Operate with lid open for cooling", "Balance is optional"], c: 1},
    {q: "The \"screen\" is listed as:", a: ["A rotor type", "A part of a centrifuge", "An opposing force", "A sample type"], c: 1},
    {q: "Which statement best matches the text's cause-effect chain for safety shutoff?", a: ["Shutoff stops rotor instantly, preventing any movement", "Shutoff stops power, but rotor continues spinning due to inertia until friction stops it", "Shutoff increases friction to stop immediately", "Shutoff opens lid automatically"], c: 1},
    {q: "Which two concepts are explicitly linked in the text as reasons a rotor keeps spinning after shutoff?", a: ["Diffusion and flotation", "Inertia and friction", "Density and viscosity", "Temperature and pressure"], c: 1},
    {q: "Which option includes ONLY items that the text lists as opposing sedimentation force?", a: ["Flotation force, frictional resistance, diffusion", "Gravity, flotation, temperature", "Pressure, friction, density", "Diffusion, inertia, voltage"], c: 0},
    {q: "Which rotor type would the text associate with minimal particle travel before pelleting?", a: ["Swinging buckets", "Vertical tube", "Fixed angle", "Almost vertical tube"], c: 2},
    {q: "Which rotor type would the text associate with improved density gradient separation due to longer travel distance?", a: ["Fixed angle", "Swinging buckets", "Vertical tube", "Lid type"], c: 1},
    {q: "Which rotor type is explicitly described as keeping tubes parallel to the rotational axis, leading to bands across diameter?", a: ["Fixed angle", "Swinging buckets", "Vertical tube", "Almost vertical tube"], c: 2},
    {q: "Which rotor type is recommended for gradient centrifugation when some sample components do not participate in the gradient?", a: ["Fixed angle", "Swinging buckets", "Vertical tube", "Almost vertical tube"], c: 3},
    {q: "If the centrifuge shakes excessively, which sequence aligns with the text?", a: ["Open lid → rebalance", "Pull plug → check balance → if unresolved, stop until serviced", "Increase speed → add water → continue", "Ignore vibration → finish run"], c: 1},
    {q: "Which safety point in the text is most directly aimed at preventing mechanical damage and injury from imbalance?", a: ["Do not open lid while rotor is moving", "Balance the centrifuge / evenly fill tubes", "Ensure a sturdy surface", "Pull the plug if shaking"], c: 1},
    {q: "Which safety point focuses on preventing access while motion continues?", a: ["Balance the centrifuge", "Ensure sturdy surface", "Do not open the lid while rotor is moving", "Fill balancing tubes with oil"], c: 2},
    {q: "In the text, the rotor is best defined as:", a: ["A lid lock only", "A motor device that houses tubes and generates rotation speed for separation", "The chamber cover", "A display screen"], c: 1},
    {q: "Which part is explicitly described as keeping the lid closed during tube breakage events?", a: ["Screen", "Latch", "Motor", "Chamber"], c: 1},
    {q: "Which part is described as being \"placed on the front casing\"?", a: ["Rotor", "Control panel", "Chamber", "Sample"], c: 1},
    {q: "Which best represents the two operation principles listed?", a: ["Heating + filtration", "Separating particles from blood/urine + separating liquids of different densities", "Cooling + sterilization", "Magnetic separation + evaporation"], c: 1},
    {q: "The text's example of separating liquids of different densities specifically involves:", a: ["Separating salt from water", "Separating lipid components from other plasma/serum components", "Separating oxygen from carbon dioxide", "Separating sand from water by filtration"], c: 1},
    {q: "Which statement is consistent with the text's scope of centrifuge use?", a: ["Used only for one test", "Used for multiple tests and treatments", "Used only for imaging", "Used only for sterilization"], c: 1},
    {q: "Which component list contains ONLY items explicitly named as centrifuge parts?", a: ["Motor, control panel, chamber, rotor, sample, latch, lid, screen, drive shaft", "Motor, MRI coil, chamber, rotor", "Control panel, autoclave, screen, drive shaft", "Lid, thermometer, rotor, microscope"], c: 0},
    {q: "Which of the following is NOT a rotor type listed?", a: ["Fixed angle", "Swinging buckets", "Vertical tube", "Spiral funnel"], c: 3},
    {q: "Which rotor type is described as the \"most widely used rotor type\"?", a: ["Swinging buckets", "Vertical tube", "Fixed angle", "Almost vertical tube"], c: 2},
    {q: "According to the text, the fundamental reason centrifugation can separate components is that rotation generates:", a: ["Heat greater than room temperature", "Forces much greater than gravity in controlled time periods", "Chemical bonds", "Optical contrast"], c: 1}
];

// 3. أسئلة المجهر (100 سؤال)
const microscopeQuestions = [
    
    {q: "What is a microscope mainly used for?", a: ["Measuring temperature", "Producing highly magnified images of small specimens", "Mixing chemicals", "Heating samples"], c: 1},
    {q: "A microscope is described in the text as a:", a: ["Simple mechanical tool", "Precision instrument", "Chemical device", "Manual counter"], c: 1},
    {q: "Which of the following is an optical subsystem of a microscope?", a: ["Stage", "Lens", "Base", "Arm"], c: 1},
    {q: "The mechanical subsystem of a microscope controls the sample position in:", a: ["One dimension only", "Two dimensions only", "Three-dimensional space X, Y, Z", "Circular motion only"], c: 2},
    {q: "Which subsystem includes transformers and light source?", a: ["Mechanical subsystem", "Electrical subsystem", "Optical subsystem", "Biological subsystem"], c: 1},
    {q: "Which subsystem may include cameras and video?", a: ["Mechanical subsystem", "Electronic subsystem", "Optical subsystem", "Base subsystem"], c: 1},
    {q: "A microscope is especially useful when objects are too small to be seen by the:", a: ["Camera", "Objective lens", "Naked eye", "Stage"], c: 2},
    {q: "The word “microscope” comes partly from the Greek word “micros,” which means:", a: ["Bright", "Small", "Lens", "Eye"], c: 1},
    {q: "Microscopy is defined as:", a: ["Repairing a microscope", "Investigation by a microscope", "Manufacturing lenses", "Measuring light intensity"], c: 1},
    {q: "The eyepiece is located at the:", a: ["Base of the microscope", "Lower end of the stage", "Upper end of the microscope", "Side of the condenser"], c: 2},
    {q: "The eyepiece consists of:", a: ["A single mirror", "A series of lenses mounted in a tube", "A metal plate", "A bulb filament"], c: 1},
    {q: "The basic function of the eyepiece is to magnify the image formed by the:", a: ["Stage clips", "Objective lens", "Base", "Diaphragm"], c: 1},
    {q: "The eyepiece magnifies the image a:", a: ["Third time", "First time", "Second time", "Fifth time"], c: 2},
    {q: "The arm of the microscope is also called the:", a: ["Barrel", "Stand or limb", "Clip", "Tube plate"], c: 1},
    {q: "The arm contains the:", a: ["Focus mechanism", "Light bulb only", "Stage clips only", "Filter disk only"], c: 0},
    {q: "The arm supports the:", a: ["Stage and body/head", "Condenser only", "Diaphragm only", "Objective lens only"], c: 0},
    {q: "The arm provides the microscope with:", a: ["Heat", "Color", "Rigidity", "Motion only"], c: 2},
    {q: "Which type of arm has the arm and body as integral parts connected solidly to the base?", a: ["Pillar", "Boom", "Fixed", "Trinocular"], c: 2},
    {q: "Which type of arm consists of a single post rising vertically from the base?", a: ["Fixed", "Boom", "Pillar", "Monocular"], c: 2},
    {q: "In the pillar type arm, the microscope body can:", a: ["Only move left and right", "Rotate about the post and move up and down", "Only rotate downward", "Only remain fixed"], c: 1},
    {q: "The boom arm is described as:", a: ["The most common arm", "A long boom type stand", "A short fixed stand", "A lens system"], c: 1},
    {q: "The boom stand allows the microscope to be aligned in:", a: ["One fixed direction", "A wide variety of configurations", "Only vertical positions", "Only horizontal positions"], c: 1},
    {q: "The least common type of arm is the:", a: ["Fixed arm", "Pillar arm", "Boom arm", "None of the above"], c: 2},
    {q: "The stage is the platform:", a: ["Above the eyepiece", "Beneath the objectives", "Inside the base", "Behind the arm"], c: 1},
    {q: "The stage is used to hold the:", a: ["Light source", "Slide or object", "Arm", "Power supply"], c: 1},
    {q: "The surface of the stage is described as:", a: ["Rough and curved", "Smooth and flat", "Soft and flexible", "Transparent and thin"], c: 1},
    {q: "The coarse adjustment is used to make:", a: ["Small changes in light", "Large changes in focus", "Small changes in color", "Large changes in stage size"], c: 1},
    {q: "The fine adjustment is used to make:", a: ["Small adjustments of focus", "Large adjustments of focus", "Changes in magnification", "Changes in illumination color"], c: 0},
    {q: "The base is the:", a: ["Upper support part", "Bottom support part", "Lens holder", "Image projector"], c: 1},
    {q: "The base provides:", a: ["Balance and rigidity", "Color and brightness", "Magnification and contrast", "Rotation and illumination"], c: 0},
    {q: "According to the text, the tube:", a: ["Holds the stage clips", "Reflects the light up to the viewer’s eyes", "Supports the base", "Contains the diaphragm"], c: 1},
    {q: "The rotating object is also called the:", a: ["Barrel", "Nosepiece", "Limb", "Aperture"], c: 1},
    {q: "The nosepiece is used to hold:", a: ["Stage clips", "Multiple objective lenses", "Only one eyepiece", "The diaphragm openings"], c: 1},
    {q: "The purpose of the nosepiece is to allow:", a: ["Quick change of objective", "Quick removal of the base", "Quick focusing of the eyepiece", "Quick movement of the arm"], c: 0},
    {q: "Objective lenses are the lenses closest to the:", a: ["Viewer’s eye", "Base", "Specimen", "Light switch"], c: 2},
    {q: "The objective lenses are considered the most important part of the:", a: ["Stage", "Microscope", "Base", "Arm"], c: 1},
    {q: "The basic function of the objective lens is to gather light passing through the:", a: ["Eyepiece", "Arm", "Specimen", "Base"], c: 2},
    {q: "The objective lens then projects the image into the:", a: ["Stage", "Body of the microscope", "Base", "Light source"], c: 1},
    {q: "Most quality microscopes use _____ for the objectives.", a: ["Plastic", "Rubber", "Glass", "Wood"], c: 2},
    {q: "The first objective lens is usually the:", a: ["Medium power objective", "High power objective", "Low power objective", "Iris objective"], c: 2},
    {q: "The low power objective usually has a magnification of:", a: ["4X", "10X", "43X", "100X"], c: 0},
    {q: "The medium power objective usually has a magnification of:", a: ["4X", "10X", "43X", "400X"], c: 1},
    {q: "The high power objective usually has a magnification of:", a: ["4X", "10X", "43X", "80X"], c: 2},
    {q: "Stage clips are used to:", a: ["Keep the slide in place", "Adjust the light intensity", "Rotate the eyepiece", "Support the arm"], c: 0},
    {q: "The condenser is located:", a: ["Above the eyepiece", "Within or below the stage", "Under the base only", "In the head only"], c: 1},
    {q: "The condenser gathers light coming from the:", a: ["Arm", "Light source", "Eyepiece", "Nosepiece"], c: 1},
    {q: "The condenser concentrates the light into a light cone onto the:", a: ["Base", "Specimen", "Arm", "Clip"], c: 1},
    {q: "Some condensers can have accessories for:", a: ["Phase contrast and polarized light", "Heating samples", "Stage cleaning", "Measuring voltage"], c: 0},
    {q: "The diaphragm is normally located:", a: ["Inside the eyepiece", "Under the stage", "On the arm", "In the base only"], c: 1},
    {q: "The diaphragm adjusts the amount of:", a: ["Magnification", "Light passing into the slide or specimen", "Stage size", "Objective number"], c: 1},
    {q: "Another name for the diaphragm is the:", a: ["Nosepiece diaphragm", "Sub-stage or aperture diaphragm", "Arm diaphragm", "Focus diaphragm"], c: 1},
    {q: "There are _____ types of diaphragm mentioned in the text.", a: ["Two", "Three", "Four", "Five"], c: 0},
    {q: "The simplest and least expensive diaphragm is the:", a: ["Iris diaphragm", "Disc diaphragm", "Polarized diaphragm", "Phase diaphragm"], c: 1},
    {q: "The disc diaphragm contains:", a: ["A glass mirror", "A rotating disk with openings of different diameters", "A bulb filament", "A movable camera"], c: 1},
    {q: "The openings in the disc diaphragm are used to:", a: ["Hold the specimen", "Limit the amount of light passing through", "Support the objective lens", "Change stage position"], c: 1},
    {q: "The better and more expensive diaphragm is the:", a: ["Disc diaphragm", "Iris diaphragm", "LED diaphragm", "Fixed diaphragm"], c: 1},
    {q: "The iris diaphragm has a:", a: ["Fixed diameter", "Continuously variable diameter", "Double lens", "Rotating stage"], c: 1},
    {q: "The iris diaphragm is usually controlled by a:", a: ["Screw", "Lever", "Clip", "Tube"], c: 1},
    {q: "The function of the iris diaphragm is to optimize:", a: ["Resolution, contrast, and sharpness", "Height, length, and width", "Voltage, power, and current", "Rotation, tilt, and balance"], c: 0},
    {q: "The light source is used to illuminate the:", a: ["Arm", "Base", "Object or specimen", "Eyepiece"], c: 2},
    {q: "The most common and least expensive illumination bulb is:", a: ["Halogen", "Tungsten", "Fluorescent", "LED"], c: 1},
    {q: "Tungsten bulbs give off a:", a: ["Blue hue", "Yellowish hue", "Green hue", "Red hue"], c: 1},
    {q: "Tungsten bulbs are typically:", a: ["5–10 watt", "15–20 watt", "40–60 watt", "80–100 watt"], c: 1},
    {q: "The hottest light source for a microscope is generally:", a: ["Tungsten", "Halogen", "Fluorescent", "LED"], c: 1},
    {q: "Halogen light is described as:", a: ["Dim and cool", "Bright, white, and concentrated", "Yellowish and weak", "Soft and blue"], c: 1},
    {q: "Halogen lamps are more expensive than:", a: ["Fluorescent lamps", "LED lamps", "Tungsten lamps", "Ring lights"], c: 2},
    {q: "The fluorescent lamp is:", a: ["Cool in temperature", "The hottest light source", "Always yellowish", "Battery operated only"], c: 0},
    {q: "Fluorescent light is especially good for observing:", a: ["Metal surfaces only", "Live specimens", "Rocks only", "Coins only"], c: 1},
    {q: "Fluorescent lamps are typically rated:", a: ["1–3 watt", "5–10 watt", "15–20 watt", "50–100 watt"], c: 1},
    {q: "A fluorescent light attached to observe from above is called a:", a: ["Disk light", "Ring light", "Cone light", "Boom light"], c: 1},
    {q: "LED stands for:", a: ["Lens Emitting Device", "Light Emitting Diode", "Low Energy Detector", "Light Expansion Display"], c: 1},
    {q: "LED light sources provide bright light with:", a: ["Very high heat", "Moderate heat", "Virtually no heat", "No brightness"], c: 2},
    {q: "LED systems are often battery operated, so they are:", a: ["Heavy", "Cordless", "Fixed to the wall", "More expensive than all others in the text"], c: 1},
    {q: "The head of the microscope connects the eyepiece to the:", a: ["Stage", "Base", "Nosepiece or turret", "Condenser"], c: 2},
    {q: "Some microscope heads allow tilting from 0° up to:", a: ["30°", "45°", "60°", "90°"], c: 2},
    {q: "A microscope with a single eyepiece is called:", a: ["Binocular", "Trinocular", "Monocular", "Universal"], c: 2},
    {q: "A microscope with two eyepieces is called:", a: ["Binocular", "Monocular", "Pillar", "Digital"], c: 0},
    {q: "A trinocular microscope includes:", a: ["Only one eyepiece", "No viewing head", "A binocular head and an additional port", "Only a camera and no eyepieces"], c: 2},
    {q: "Most microscopes are called light microscopes because they rely on:", a: ["Heat", "Sound", "Light", "Pressure"], c: 2},
    {q: "Which of the following is listed as a category of microscope?", a: ["Hydraulic microscope", "Compound microscope", "Steam microscope", "Magnetic microscope"], c: 1},
    {q: "The compound microscope is also referred to as a:", a: ["Dissecting microscope", "Biological or research microscope", "Metallurgical lamp", "Ring microscope"], c: 1},
    {q: "The compound microscope is referred to as a:", a: ["Low power microscope", "High power microscope", "Thermal microscope", "Portable microscope"], c: 1},
    {q: "The magnification range of a compound microscope is about:", a: ["10x to 80x", "40x to 1000x", "5x to 20x", "1000x to 5000x"], c: 1},
    {q: "Some compound microscopes can go up to:", a: ["200x", "500x", "1500x or 2000x", "80x only"], c: 2},
    {q: "Much serious work of a compound microscope is done at:", a: ["10x to 40x", "80x to 100x", "400x to 500x", "1000x to 2000x only"], c: 2},
    {q: "The compound microscope has:", a: ["Two separate light paths", "A single light path through a series of lenses", "No objective lenses", "Only one magnifying lens"], c: 1},
    {q: "The image in a compound microscope is seen as if it were about:", a: ["10 inches (250 mm) from the eye", "1 inch from the eye", "1 meter from the eye", "50 inches from the eye"], c: 0},
    {q: "The image produced at the eye by a compound microscope is usually:", a: ["Three-dimensional and upright", "Two-dimensional, reversed, and upside down", "Colored and moving", "Enlarged but not reversed"], c: 1},
    {q: "The most used light method in a compound microscope is:", a: ["Reflection from above", "Trans-illumination", "Side illumination only", "Infrared illumination"], c: 1},
    {q: "Trans-illumination means light is projected from:", a: ["Above", "The side", "Below", "Behind the head"], c: 2},
    {q: "At 400x magnification, a compound microscope can show detail at the:", a: ["Planetary level", "Cellular level", "Mechanical level only", "Surface level only"], c: 1},
    {q: "Stereo microscopes are the _____ most common type of microscope.", a: ["First", "Second", "Third", "Least"], c: 1},
    {q: "Stereo microscopes are also referred to as:", a: ["Research microscopes", "Dissection or inspection microscopes", "Electron beam microscopes", "Phase contrast microscopes only"], c: 1},
    {q: "The stereo microscope is considered a:", a: ["High power microscope", "Low power microscope", "Digital microscope only", "Phase microscope only"], c: 1},
    {q: "The magnification range of a stereo microscope is about:", a: ["10x to 80x", "40x to 1000x", "100x to 1500x", "500x to 2000x"], c: 0},
    {q: "The most popular magnification range for stereo microscopes is:", a: ["1x to 5x", "10x to 40x", "100x to 500x", "500x to 1000x"], c: 1},
    {q: "A stereo microscope produces a true:", a: ["2-D image", "Colored image only", "Stereo image", "Reversed image only"], c: 2},
    {q: "A stereo microscope has:", a: ["One light path only", "Two separate light paths", "No light path", "Three light paths only"], c: 1},
    {q: "The image produced by a stereo microscope is:", a: ["Two-dimensional", "Upside down", "Three-dimensional", "Invisible without a camera"], c: 2},
    {q: "Most stereo microscopes have built-in illumination from:", a: ["Top only", "Bottom only", "Both top and bottom", "Neither top nor bottom"], c: 2}
];

// 4. أسئلة جهاز التقطير (100 سؤال)
const distillerQuestions = [
 
    { q: "What is distillation primarily described as?", a: ["A filtration process", "A separation process using heating and condensation", "A crystallization process", "A centrifugation process"], c: 1 },
    { q: "Distillation involves first heating a liquid to its:", a: ["Freezing point", "Melting point", "Boiling point", "Sublimation point"], c: 2 },
    { q: "After heating, the vapour is transferred to:", a: ["A burner", "A different portion of the apparatus", "A balance", "A beaker of ice"], c: 1 },
    { q: "The vapour is then:", a: ["Filtered and dried", "Condensed and collected", "Neutralized and titrated", "Frozen and weighed"], c: 1 },
    { q: "Distillation is useful for separating mixtures of liquids when components have different:", a: ["Colors", "Densities", "Boiling points", "Volumes"], c: 2 },
    { q: "Chemically, distillation is the principal method for:", a: ["Measuring pH", "Purifying liquids", "Producing solids", "Identifying metals"], c: 1 },
    { q: "Successful distillation depends on the difference in boiling points and therefore difference in:", a: ["Viscosity", "Vapour pressures", "Surface tension", "Electrical conductivity"], c: 1 },
    { q: "Successful distillation also depends on the:", a: ["Color of the flask", "Type of apparatus used", "Shape of the beaker", "Brand of thermometer"], c: 1 },
    { q: "Successful distillation also depends on the:", a: ["Care exercised by the experimentalist", "Color of cooling water", "Size of labels", "Room lighting"], c: 0 },
    { q: "Distillation works by exploiting different:", a: ["Densities of solids", "Boiling temperatures of liquids", "Magnetism of liquids", "pH values"], c: 1 },
    { q: "To separate liquids by distillation, you first heat them in a:", a: ["Test tube", "Flask", "Petri dish", "Funnel"], c: 1 },
    { q: "The more volatile liquid is the one with the:", a: ["Higher boiling point", "Lower boiling point", "Higher density", "Lower viscosity"], c: 1 },
    { q: "Typically, the more volatile liquid will:", a: ["Freeze first", "Evaporate first", "Condense first", "Crystallize first"], c: 1 },
    { q: "The vapor passes into a:", a: ["Drying oven", "Condensing column", "Balance chamber", "Separatory funnel"], c: 1 },
    { q: "In the condensing column, the vapor reverts into a liquid by:", a: ["Subliming", "Condensing on cool glass", "Reacting with air", "Absorbing light"], c: 1 },
    { q: "After condensing, it trickles into a:", a: ["Collection flask", "Burette", "Pipette", "Crucible"], c: 0 },
    { q: "Heating further causes the less volatile liquids to:", a: ["Distill at lower temperatures", "Distill at higher temperatures", "Stop evaporating", "Become solids immediately"], c: 1 },
    { q: "The two main kinds of distillation mentioned are:", a: ["Vacuum and steam", "Simple and fractional", "Chemical and physical", "Batch and continuous only"], c: 1 },
    { q: "A pure liquid has a constant boiling point as long as liquid and vapour are in:", a: ["Turbulence", "Equilibrium", "Darkness", "Motionless air"], c: 1 },
    { q: "In simple distillation of a pure substance, as temperature rises, vapour pressure:", a: ["Decreases", "Increases", "Stays constant", "Disappears"], c: 1 },
    { q: "As vapour expands, it passes out of the heated portion until it contacts the:", a: ["Hot plate", "Cold surface of the water-cooled condenser", "Rubber stopper", "Measuring cylinder"], c: 1 },
    { q: "When cooled, the vapour:", a: ["Turns into a solid", "Condenses", "Becomes plasma", "Explodes"], c: 1 },
    { q: "After condensation, the liquid passes down the condenser into the:", a: ["Receiver", "Burner", "Filter paper", "Clamp"], c: 0 },
    { q: "A water distiller consists of components shown in:", a: ["Figure 3", "Figure 1", "Figure 2 only", "No figure is referenced"], c: 1 },
    { q: "The vapour generator is also called the:", a: ["Condenser", "Boiling tank", "Filter", "Receiver adapter"], c: 1 },
    { q: "The vapour generator is the container where the water to be distilled is:", a: ["Frozen", "Stored", "Colored", "Neutralized"], c: 1 },
    { q: "The water level device allows the quantity of water to be regulated inside the:", a: ["Condenser", "Vapour generator", "Distilled water container", "Thermometer bulb"], c: 1 },
    { q: "The control valve regulates the flow of water towards the:", a: ["Condenser", "Vapour generator tank", "Distilled water container", "Activated carbon filter"], c: 1 },
    { q: "The control valve can be described as:", a: ["Optical", "Mechanical or electromechanical", "Purely chemical", "Only plastic"], c: 1 },
    { q: "The hydraulic connection is the network that supplies water in liquid phase to the:", a: ["Filter", "Vapour generator tank", "Collection flask", "Thermometer adapter"], c: 1 },
    { q: "Water in liquid phase refers to water inside the:", a: ["Condenser", "Vapour generator tank", "Distilled water container", "Fractionating column"], c: 1 },
    { q: "Water in the vapour generator tank receives thermal energy from the:", a: ["Glass beads", "Immersion resistors", "Thermometer", "Rubber tubing only"], c: 1 },
    { q: "Water is converted to vapour when required temperature and pressure conditions are:", a: ["Ignored", "Met", "Removed", "Lowered to zero"], c: 1 },
    { q: "Immersion resistors generate heat when an electrical current:", a: ["Stops completely", "Circulates through them", "Is converted into light only", "Is reflected by glass beads"], c: 1 },
    { q: "The refrigeration water outlet carries the water used for:", a: ["Mixing chemicals", "Condensing the water vapour", "Heating the boiling flask", "Measuring pH"], c: 1 },
    { q: "Refrigeration water removes thermal energy from vapour by:", a: ["Heating", "Cooling", "Ionizing", "Filtering"], c: 1 },
    { q: "The condenser is the device in which vapour:", a: ["Gains thermal energy", "Loses thermal energy and returns to liquid", "Turns into gas permanently", "Becomes solid directly"], c: 1 },
    { q: "Distillers have activated carbon filters located at the exit of the:", a: ["Thermometer", "Condenser or collector", "Boiling flask only", "Fractionating column only"], c: 1 },
    { q: "Activated carbon filters eliminate:", a: ["Metals only", "Flavours or particles", "Water entirely", "Heat completely"], c: 1 },
    { q: "The distilled water container is where the fluid completing the distillation process is:", a: ["Heated", "Collected", "Evaporated again", "Burned"], c: 1 },
    { q: "Distilled water must be stored in special plastic containers to avoid:", a: ["Temperature change", "Ionic contamination", "Evaporation", "Light exposure"], c: 1 },
    { q: "The text states there are two types of distillation:", a: ["Steam and vacuum", "Simple and fractional", "Flash and azeotropic", "Destructive and constructive"], c: 1 },
    { q: "In a simple distillation setup, the apparatus includes a:", a: ["Separatory funnel", "Boiling flask (round-bottom flask)", "Centrifuge tube", "Mortar and pestle"], c: 1 },
    { q: "The boiling flask is attached to an adapter holding a:", a: ["pH meter", "Thermometer", "Stopwatch", "Spectrometer"], c: 1 },
    { q: "The thermometer is used to determine the:", a: ["Density of the liquid", "Boiling temperature of the liquid", "Mass of the flask", "Color intensity"], c: 1 },
    { q: "The adapter connects to a:", a: ["Balance", "Condenser", "Sieve", "Magnetic stirrer only"], c: 1 },
    { q: "In the condenser, cold water is constantly:", a: ["Removed and discarded before entry", "Passed through", "Turned into steam immediately", "Mixed with distillate"], c: 1 },
    { q: "The condenser leads into a collection flask for the:", a: ["Unpurified liquid", "Purified liquid", "Solid residue only", "Gas mixture only"], c: 1 },
    { q: "Fractional distillation is like simple distillation except that a ___ is placed between boiling flask and condenser.", a: ["Filter paper", "Fractionating column", "Beaker", "Clamp"], c: 1 },
    { q: "The fractionating column is usually filled with:", a: ["Sand only", "Glass or plastic beads", "Cotton wool only", "Metal powder"], c: 1 },
    { q: "The beads improve the separation between liquids being:", a: ["Mixed", "Distilled", "Frozen", "Neutralized"], c: 1 },
    { q: "Fractional distillation gives better separation because beads provide:", a: ["Vacuum chambers", "Theoretical plates", "Strong magnets", "Extra burners"], c: 1 },
    { q: "On theoretical plates, the refluxing liquid can:", a: ["Only freeze", "Condense, re-evaporate, and condense again", "Only react chemically", "Only turn into solid"], c: 1 },
    { q: "This repeated condense/re-evaporate action essentially distills the compound:", a: ["Once only", "Over and over", "Not at all", "Only at room temperature"], c: 1 },
    { q: "In a fractionating column, the more volatile liquids tend to push towards the:", a: ["Bottom", "Top", "Middle only", "Outside of the column"], c: 1 },
    { q: "In a fractionating column, the more boiling (less volatile) liquids tend to stay towards the:", a: ["Top", "Bottom", "Outside of condenser", "Thermometer bulb"], c: 1 },
    { q: "Adding more theoretical plates generally makes distillation:", a: ["Shorter and colder", "Take longer", "Impossible", "Independent of energy"], c: 1 },
    { q: "Adding more theoretical plates also generally requires:", a: ["Less energy to re-evaporate liquid", "More energy to re-evaporate liquid", "No heating at all", "Only sunlight"], c: 1 },
    { q: "The text notes energy cost is more of a concern in:", a: ["Academic lab distillations", "Industrial distillations", "Household cooking", "Measuring exercises"], c: 1 },
    { q: "The comparison table lists an advantage of simple distillation as:", a: ["Much better separation than fractional", "Simpler setup than fractional", "Requires more energy", "Longer distillation time"], c: 1 },
    { q: "Another advantage of simple distillation is:", a: ["Faster distillation time", "Better theoretical plates", "Works with small boiling point differences", "Needs beads always"], c: 0 },
    { q: "Another advantage of simple distillation is that it:", a: ["Consumes more energy", "Consumes less energy", "Requires vacuum", "Requires multiple columns"], c: 1 },
    { q: "An advantage of fractional distillation is:", a: ["Poor separation", "Much better separation between liquids than simple distillation", "Always faster", "No energy needed"], c: 1 },
    { q: "Another advantage of fractional distillation is it can more readily purify:", a: ["Only single pure liquids", "Complex mixtures", "Only solids", "Only gases"], c: 1 },
    { q: "A disadvantage of simple distillation is it requires liquids to have:", a: ["No boiling point difference", "Large boiling point differences (>70°C)", "Identical vapour pressures", "Very low melting points"], c: 1 },
    { q: "Another disadvantage of simple distillation is it:", a: ["Gives poorer separation than fractional distillation", "Gives better separation than fractional distillation", "Needs beads", "Needs industrial columns"], c: 0 },
    { q: "The table states simple distillation only works well with relatively:", a: ["Dirty mixtures", "Pure samples", "Solid-only mixtures", "Gas-only mixtures"], c: 1 },
    { q: "A disadvantage of fractional distillation is a:", a: ["Simpler setup than simple", "More complicated setup than simple distillation", "Lower separation power", "No condenser needed"], c: 1 },
    { q: "Another disadvantage of fractional distillation is it:", a: ["Takes longer for liquids to distill", "Always finishes instantly", "Elimates the need for heating", "Cannot separate liquids"], c: 0 },
    { q: "Another disadvantage of fractional distillation is it:", a: ["Consumes less energy than simple distillation", "Consumes more energy than simple distillation", "Uses no energy", "Removes need for water cooling"], c: 1 },
    { q: "Simple distillation is best used for separating relatively pure liquids with:", a: ["Smaller boiling point separations", "Large boiling differences", "No boiling differences", "Identical densities only"], c: 1 },
    { q: "Simple distillation is also best used for liquids with:", a: ["Only gas impurities", "Solid impurities", "Only color impurities", "Only magnetic impurities"], c: 1 },
    { q: "Fractional distillation is best used for separating:", a: ["Complex mixtures of liquids", "Single pure liquids only", "Solids from solids", "Metals from salts"], c: 0 },
    { q: "Fractional distillation is best used when boiling point separations are:", a: ["Very large only", "Smaller", "Infinite", "Not relevant"], c: 1 },
    { q: "Distillation technique includes transferring vapour and then:", a: ["Burning it", "Condensing it", "Filtering it directly", "Freezing it in the flask"], c: 1 },
    { q: "The collected condensed liquid is called the:", a: ["Residue", "Condensate", "Reactant", "Catalyst"], c: 1 },
    { q: "The condensed liquid is collected in another:", a: ["Container", "Burner", "Stirrer", "Thermometer"], c: 0 },
    { q: "The text says distillation is one of the most useful techniques for separating:", a: ["A mixture of solids", "A mixture of liquids", "A mixture of metals", "A mixture of powders"], c: 1 },
    { q: "Distillation depends on differences in vapour pressures because vapour pressure relates to:", a: ["Boiling behaviour described in the text", "Color of the liquid", "Mass of glassware", "Labeling style"], c: 0 },
    { q: "The more volatile liquid typically distills at:", a: ["Higher temperatures", "Lower temperatures", "Any random temperature", "Only at 0°C"], c: 1 },
    { q: "The less volatile liquids distill at:", a: ["Lower temperatures", "Higher temperatures", "Only at freezing point", "Only without condenser"], c: 1 },
    { q: "In a pure liquid distillation, vapour passes out of the heated portion until it contacts a:", a: ["Hot metal surface", "Cold surface of a water-cooled condenser", "Dry paper surface", "Warm plastic surface"], c: 1 },
    { q: "In the condenser, vapour is cooled and then:", a: ["Turns into a different chemical", "Condenses", "Becomes solid metal", "Explodes"], c: 1 },
    { q: "The distillate flows down the condenser into the:", a: ["Receiver", "Boiling flask", "Fractionating column", "Water inlet"], c: 0 },
    { q: "Component (7) in the water distiller list is the:", a: ["Filter", "Refrigeration water outlet", "Water level", "Vapour generator"], c: 3 },
    { q: "Component (8) in the water distiller list is the:", a: ["Condenser", "Control valve", "Immersion resistor", "Distilled water container"], c: 0 },
    { q: "Component (9) in the water distiller list is the:", a: ["Filter", "Hydraulic connection", "Vapour generator", "Water level"], c: 0 },
    { q: "Component (10) in the water distiller list is the:", a: ["Thermometer adapter", "Distilled water container", "Glass bead column", "Refrigeration outlet"], c: 1 },
    { q: "The vapour generator (boiling tank) stores:", a: ["Distilled water only", "Water to be distilled", "Activated carbon", "Glass beads"], c: 1 },
    { q: "The water level device allows regulation of:", a: ["Temperature only", "Quantity of water", "Colour of vapour", "Shape of condenser"], c: 1 },
    { q: "The control valve regulates:", a: ["Electrical current", "Flow of water towards the vapour generator tank", "Glass bead size", "Condenser length"], c: 1 },
    { q: "The hydraulic connection supplies water in:", a: ["Solid phase", "Liquid phase", "Plasma phase", "Crystal phase"], c: 1 },
    { q: "The immersion resistors generate heat due to:", a: ["Mechanical friction", "Electrical current circulation", "Sunlight absorption", "Chemical reaction with water"], c: 1 },
    { q: "Refrigeration water is used to:", a: ["Heat the vapour", "Condense vapour by removing thermal energy", "Add ions to water", "Make beads float"], c: 1 },
    { q: "Activated carbon filters are used to eliminate:", a: ["Boiling points", "Flavours or particles", "Condensers", "Vapour pressure differences"], c: 1 },
    { q: "Distilled water must be stored in special plastic containers to avoid:", a: ["Becoming colder", "Ionic contamination", "Becoming heavier", "Evaporating instantly"], c: 1 },
    { q: "In simple distillation, the apparatus includes an adapter holding a:", a: ["Stir bar", "Thermometer", "Filter pad", "Bead pack"], c: 1 },
    { q: "In fractional distillation, placing a fractionating column between boiling flask and condenser improves separation by:", a: ["Removing the need for cooling water", "Providing theoretical plates for repeated condensation and evaporation", "Eliminating boiling point differences", "Turning vapour into solids"], c: 1 },
    { q: "The table indicates simple distillation gives:", a: ["Better separation than fractional", "Poorer separation than fractional", "Identical separation always", "No separation at all"], c: 1 },
    { q: "The table indicates fractional distillation is best for mixtures with:", a: ["Large boiling point differences (>70°C) only", "Smaller boiling point separations and more complex mixtures", "Only solid impurities", "Only pure single liquids"], c: 1 }
];

// 5. أسئلة الفرن (Oven) - فارغة حالياً حتى ترسل لي الملف
const ovenQuestions = [
    
    {q: "The oven is used in a laboratory mainly for:", a: ["Centrifuging samples", "Drying and sterilizing glass and metal containers/materials", "Measuring blood pressure", "Freezing reagents"], c: 1},
    {q: "The ovens operate between room temperature and:", a: ["120°C", "200°C", "350°C", "500°C"], c: 2},
    {q: "The oven is also known as a:", a: ["Water bath", "Hot air oven", "Incubator only", "Autoclave"], c: 1},
    {q: "Heat is generated through sets of:", a: ["Fans", "Electrical resistors", "Thermometers", "Fuses"], c: 1},
    {q: "Electrical resistors transfer thermal energy to the:", a: ["Lid", "Chamber", "Control panel", "Coat"], c: 1},
    {q: "The resistors are located in the:", a: ["Upper part", "Lower part", "Door", "Shelves"], c: 1},
    {q: "Heat is transferred and distributed by:", a: ["Filtration", "Natural or forced convection", "Sedimentation", "Diffusion"], c: 1},
    {q: "Forced convection is associated with ovens that have:", a: ["Internal ventilators", "External thermometers only", "No chamber", "No resistors"], c: 0},
    {q: "The oven consists of two parts:", a: ["Plastic and glass parts", "Mechanical part and electrical part", "Liquid and solid parts", "Heating and cooling parts"], c: 1},
    {q: "The coat is made of aluminum or stainless steel because it resists:", a: ["Water evaporation", "Mechanical shocks and oxidation", "Magnetic fields", "Electrical leakage only"], c: 1},
    {q: "The coat has a rectangle solid shape to be:", a: ["Harder to move", "Easily placed anywhere", "Used underwater", "Used only in corners"], c: 1},
    {q: "The coat contains isolator material surfaces to prevent:", a: ["Dust entering", "Heat getting outside", "Air circulation", "Timer operation"], c: 1},
    {q: "Fiber glass is mentioned as having:", a: ["One type only", "Two types", "Four types", "No types"], c: 1},
    {q: "The two fiber glass types are:", a: ["White and black", "Brown and yellow", "Red and green", "Thick and thin"], c: 1},
    {q: "Brown fiber glass is described as:", a: ["Expensive and safe", "Cheap but dangerous", "Rare and harmless", "Liquid and unstable"], c: 1},
    {q: "Brown fiber glass is dangerous because it causes:", a: ["Skin burns", "Inflammation in the chest", "Eye blindness", "Hearing loss"], c: 1},
    {q: "Yellow fiber glass is described as:", a: ["More dangerous than brown", "Serious but less dangerous than brown", "Completely safe", "Not available"], c: 1},
    {q: "The text advises caution with yellow fiber glass due to:", a: ["Sensitivity; wear gloves", "High voltage", "Strong magnetism", "Water absorption"], c: 0},
    {q: "One advantage of fiber glass is that it is a good:", a: ["Electrical conductor", "Heat insulator", "Acid neutralizer", "Light reflector"], c: 1},
    {q: "Fiber glass is used because it prevents heat from:", a: ["Entering the oven", "Passing from inside to outside", "Passing from outside to inside", "Forming convection"], c: 1},
    {q: "Fiber glass helps to:", a: ["Maintain the internal temperature", "Reduce electrical current", "Increase corrosion", "Remove moisture chemically"], c: 0},
    {q: "Fiber glass is described as having:", a: ["Very good heat conduction", "Very bad conduction heat", "Perfect heat conduction", "Zero insulation"], c: 1},
    {q: "The container material must have:", a: ["Very high heat conduction", "Very low heat conduction", "High flammability", "High porosity"], c: 1},
    {q: "The container should be resistant to:", a: ["Mechanical shock", "Light reflection", "Sound vibration", "Gravity"], c: 0},
    {q: "The container volume must be enough to contain a certain amount of:", a: ["Water", "Tools to be sterilized or cleaned", "Fuel", "Explosives"], c: 1},
    {q: "The shelves (mesh) are made of:", a: ["Rubber", "Aluminum or steel", "Wood", "Glass"], c: 1},
    {q: "The mesh contains holes to increase:", a: ["Electrical resistance", "Thermal conductivity", "Corrosion rate", "Viscosity"], c: 1},
    {q: "The used supply is:", a: ["110V-60Hz", "220V-50Hz", "380V-60Hz", "12V-DC"], c: 1},
    {q: "The power supply section mentions a step down transformer and:", a: ["Cooling fan", "Rectifying circuit (AC to DC convert)", "Lubrication unit", "Pressure valve"], c: 1},
    {q: "AC-to-DC conversion is used to run the:", a: ["Shelves", "Control panel (parameters/numeric departments)", "Fiber glass", "Coat"], c: 1},
    {q: "Heating is produced by current passing through a conductor having:", a: ["Low resistance", "High resistance to current flow", "No resistance", "No conductor"], c: 1},
    {q: "The heater is placed in the:", a: ["Lid", "Base of the instrument", "Door", "Control panel"], c: 1},
    {q: "A heater element characteristic listed is:", a: ["High resistance", "High flammability", "Water solubility", "Optical transparency"], c: 0},
    {q: "Another heater element characteristic is:", a: ["Electrical insulation", "Acid production", "Magnetic attraction", "Sound absorption"], c: 0},
    {q: "Another heater element characteristic is:", a: ["Thermal conductivity", "Electrical discharge", "Chemical reactivity", "Optical reflection"], c: 0},
    {q: "A thermostat is described as:", a: ["A shelf support", "A heat sensor connected directly with the heater", "A fuse type", "A mesh component"], c: 1},
    {q: "The thermostat separates the heater in certain degrees and is used to:", a: ["Increase corrosion", "Protect the device", "Reduce insulation", "Increase vibration"], c: 1},
    {q: "Temperature indicator methods include:", a: ["Timer and fuse", "Thermometer and thermocouple", "Mesh and coat", "Rotor and latch"], c: 1},
    {q: "A thermometer is used to measure:", a: ["Temperature of material", "Voltage of supply", "Time of sterilization", "Speed of ventilation"], c: 0},
    {q: "A thermocouple identifies:", a: ["External temperature only", "Internal temperature", "Mesh hole size", "Fuse current rating"], c: 1},
    {q: "Mechanical thermometer principle depends on:", a: ["Diffusion rate", "Expansion factor of materials like mercury", "Air pressure only", "Electrical resistance only"], c: 1},
    {q: "Mercury is used more than alcohol because it has:", a: ["Lower cost only", "Wide thermal range (70-350)", "Lower density than alcohol", "No expansion"], c: 1},
    {q: "The thermal range for mercury given in the text is:", a: ["0-100", "70-350", "20-120", "100-500"], c: 1},
    {q: "Electrical thermometer principle depends on:", a: ["Gravity convection", "Electrical conductive property of the material", "Pelleting", "Oxidation rate"], c: 1},
    {q: "Resistors are described as heating elements transforming:", a: ["Thermal energy into electrical energy", "Electrical energy into thermal energy", "Light energy into chemical energy", "Mechanical energy into sound"], c: 1},
    {q: "The timer has two types:", a: ["Digital and analog", "Electrical and mechanical", "Chemical and physical", "Infrared and ultraviolet"], c: 1},
    {q: "The timer range is:", a: ["1-10 min", "5-60 min", "60-120 min", "0-5 min"], c: 1},
    {q: "The timer gives the required period of time for:", a: ["Cooling", "Sterilization", "Lubrication", "Painting the coat"], c: 1},
    {q: "The fuse protects the circuit from:", a: ["Low current only", "High current, high loads, short circuits", "Dust only", "Heat loss only"], c: 1},
    {q: "The control panel contains several elements; the most important is:", a: ["Thermocouple wire", "Indicator power lamp (usually green)", "Shelf mesh", "Fiber glass layer"], c: 1},
    {q: "The indicator heater lamp is usually:", a: ["Green", "Red", "Yellow", "Blue"], c: 1},
    {q: "The control panel includes a:", a: ["Switch on/off", "Rotor", "Drive shaft", "Chamber lock"], c: 0},
    {q: "The control panel includes a:", a: ["Timer", "Brown fiber glass", "Container volume gauge", "Acid detector"], c: 0},
    {q: "The control panel includes:", a: ["Selected temperature", "Sample holder", "Flotation force sensor", "Density bucket"], c: 0},
    {q: "The text lists types of oven by operation as:", a: ["Wet and dry", "Natural convection and forced convection", "Mechanical and electrical", "Large and small"], c: 1},
    {q: "Natural convection is also called:", a: ["Gravity convection", "Magnetic convection", "Electric convection", "Chemical convection"], c: 0},
    {q: "Forced convection is listed as a type of oven operation:", a: ["Yes", "No", "Only for water bath", "Only for centrifuge"], c: 0},
    {q: "One application of the oven is:", a: ["Density gradient separation", "Drying", "Sedimentation", "Sonication"], c: 1},
    {q: "Another application is sterilizing:", a: ["Plastics only", "Glass and metal containers/materials used for tests", "Only liquids", "Only paper"], c: 1},
    {q: "The notification says to avoid using:", a: ["Stainless steel containers", "Flammable or explosive materials in the oven", "Thermometers", "Fuses"], c: 1},
    {q: "The notification also advises avoiding:", a: ["Natural convection", "Spills of acid solutions or corrosive vapors inside the oven", "Internal temperature measurement", "Gloves"], c: 1},
    {q: "Acid spills/corrosive vapors should be avoided to prevent corrosion of:", a: ["Only the coat", "Surfaces and interior shelves", "Only the thermometer", "Only the fuse"], c: 1},
    {q: "Personal protection elements recommended include:", a: ["Cotton gloves only", "Insulated gloves, safety glasses, and tongs", "Earplugs only", "Lab coat only"], c: 1},
    {q: "Tongs are recommended for:", a: ["Increasing convection", "Placing/removing substances or materials inside the drying oven", "Measuring internal temperature", "Turning off the fuse"], c: 1},
    {q: "The coat is made of aluminum or stainless steel partly because it resists:", a: ["Inertia", "Oxidation", "Diffusion", "Pelleting"], c: 1},
    {q: "The coat's isolator material surfaces mainly prevent:", a: ["Electrical flow", "Heat leakage to the outside", "Timer drift", "Lamp color change"], c: 1},
    {q: "Brown fiber glass requires caution mainly because it may cause:", a: ["Tooth decay", "Chest inflammation", "Liquid evaporation", "Short circuits"], c: 1},
    {q: "Yellow fiber glass is available widely and is:", a: ["Harmless", "Serious but less dangerous than brown", "More dangerous than brown", "Only decorative"], c: 1},
    {q: "Yellow fiber glass handling advice includes:", a: ["Wear gloves", "Do not use gloves", "Heat it first", "Soak it in acid"], c: 0},
    {q: "Fiber glass is suitable for insulation because it has:", a: ["High heat conduction", "Very bad conduction heat", "High flammability", "High electrical conductivity"], c: 1},
    {q: "The container should be stainless steel because it is:", a: ["Highly conductive to heat", "Very low conductive to heat and resistant to mechanical shock", "Explosive-proof", "Transparent"], c: 1},
    {q: "The mesh holes are intended to increase:", a: ["Corrosion", "Thermal conductivity", "Electrical shorting", "Chest inflammation risk"], c: 1},
    {q: "The power supply information mentions running the control panel for:", a: ["Pelleting settings", "Parameters, numeric or other departments (modern fashion)", "Rotor speed settings", "Lid lock pressure"], c: 1},
    {q: "The heater produces heat by a conductor with high resistance; this describes:", a: ["Evaporation", "Electrical heating by current flow through a high-resistance conductor", "Filtration", "Sedimentation"], c: 1},
    {q: "The thermostat is connected directly with the heater and can:", a: ["Increase oxidation", "Separate the heater at certain degrees", "Increase mesh holes", "Reduce resistor count"], c: 1},
    {q: "The thermostat is used to:", a: ["Protect the device", "Increase drying time", "Increase acid spills", "Reduce convection"], c: 0},
    {q: "The temperature indicator includes a thermometer and a:", a: ["Rotor", "Thermocouple", "Latch", "Fuse"], c: 1},
    {q: "The thermometer measures:", a: ["Temperature of material", "Internal voltage", "Shelf corrosion", "Fuse load"], c: 0},
    {q: "The thermocouple identifies:", a: ["Internal temperature", "External oxidation", "Timer range", "Coat shape"], c: 0},
    {q: "The control panel includes indicator lamps and also:", a: ["Switch on/off, timer, selected temperature", "Rotor buckets, latch, lid", "Sample tubes, gradients, diffusion", "Water level and heater motor"], c: 0},
    {q: "Heat distribution occurs by convection, and forced convection is specifically linked to:", a: ["Coats made of stainless steel", "Ovens with internal ventilators", "Brown fiber glass only", "Timers with mechanical type only"], c: 1},
    {q: "Which statement best matches the role of the isolator material in the coat?", a: ["It increases oxidation", "It prevents heat from getting outside", "It increases thermal conduction outward", "It reduces the need for resistors"], c: 1},
    {q: "Which option correctly identifies BOTH fiber glass types mentioned?", a: ["Blue and green", "Brown and yellow", "Red and white", "Steel and aluminum"], c: 1},
    {q: "The text labels brown fiber glass as \"cheap\" but dangerous mainly due to:", a: ["Electrical shock risk", "Chest inflammation risk", "Short circuit risk", "Explosion risk"], c: 1},
    {q: "Yellow fiber glass is described as \"serious\" but less dangerous than brown, and requires:", a: ["No precautions", "Wearing gloves because of sensitivity", "Heating to 350°C before touching", "Wearing metal tongs only"], c: 1},
    {q: "The phrase \"very bad conduction heat\" indicates fiber glass is good for:", a: ["Heat generation", "Heat insulation", "Electrical conduction", "Increasing thermal loss"], c: 1},
    {q: "The container material requirement combines low heat conduction with:", a: ["High magnetic permeability", "Resistance to mechanical shock", "High flammability", "High corrosion creation"], c: 1},
    {q: "The shelves (mesh) material and design choice (holes) is intended to:", a: ["Lower thermal conductivity", "Increase thermal conductivity", "Stop convection", "Prevent internal temperature measurement"], c: 1},
    {q: "The power supply section mentions step down transformer + rectifying circuit to:", a: ["Run the control panel in modern fashion", "Increase mechanical shocks resistance", "Create chest inflammation", "Decrease internal temperature automatically"], c: 0},
    {q: "The heater is described as being placed only in the:", a: ["Door", "Base of the instrument", "Control panel", "Upper coat"], c: 1},
    {q: "Which list contains ONLY heater element characteristics exactly as stated?", a: ["High resistance; electrical insulation; thermal conductivity", "Low resistance; chemical insulation; thermal invisibility", "High voltage; low heat; high pressure", "High density; diffusion; inertia"], c: 0},
    {q: "The thermostat is a heat sensor connected directly to the heater and can:", a: ["Separate the heater in certain degrees", "Increase acid vapor production", "Replace the fuse", "Replace the container"], c: 0},
    {q: "The two temperature indicator methods are thermometer and thermocouple; their roles are:", a: ["Both measure external temperature only", "Thermometer measures temperature of material; thermocouple identifies internal temperature", "Thermometer identifies internal temperature; thermocouple measures shelf temperature", "Both identify humidity only"], c: 1},
    {q: "Mechanical thermometer principle depends on:", a: ["Electrical conductivity", "Expansion factor of materials like mercury", "Forced convection", "Mesh holes"], c: 1},
    {q: "Mercury is used more than alcohol because:", a: ["It is lighter", "It has a wide thermal range (70-350)", "It conducts electricity better", "It prevents corrosion"], c: 1},
    {q: "Electrical thermometer principle depends on:", a: ["Expansion of liquid", "Electrical conductive property of material", "Oxidation of coat", "Friction in ventilators"], c: 1},
    {q: "The timer types and range are stated as:", a: ["Electrical/mechanical; 5-60 min", "Digital/analog; 1-10 min", "Chemical/physical; 60-120 min", "Manual/automatic; 0-5 min"], c: 0},
    {q: "Fuse function is stated as protection from:", a: ["Low current, low load, open circuit", "High current, high loads, short circuits", "Heat loss, convection, diffusion", "Oxidation, corrosion, insulation"], c: 1},
    {q: "On the control panel, the power indicator lamp is usually:", a: ["Red", "Green", "Yellow", "Black"], c: 1},
    {q: "Safety notification includes avoiding flammables/explosives and acids/corrosive vapors, and using PPE including:", a: ["Boots only", "Insulated gloves, safety glasses, and tongs", "Earplugs only", "Paper towels only"], c: 1}

];